/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./src/layouts/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'col-span-1',
    'col-span-2',
    'col-span-3',
    'col-span-4',
    'col-span-5',
    'col-span-6',
    'col-span-7',
    'col-span-8',
    'col-span-9',
    'col-span-10',
    'col-span-11',
    'col-span-12',
    'col-span-13',
    'col-span-14',
    'col-span-15',
    'col-span-16',
    'col-span-17',
    'col-span-18',
    'col-span-19',
    'col-span-20',
    'col-span-21',
    'col-span-22',
    'col-span-23',
    'col-span-24',
    'sm:col-span-1',
    'sm:col-span-2',
    'sm:col-span-3',
    'sm:col-span-4',
    'sm:col-span-5',
    'sm:col-span-6',
    'sm:col-span-7',
    'sm:col-span-8',
    'sm:col-span-9',
    'sm:col-span-10',
    'sm:col-span-11',
    'sm:col-span-12',
    'sm:col-span-13',
    'sm:col-span-14',
    'sm:col-span-15',
    'sm:col-span-16',
    'sm:col-span-17',
    'sm:col-span-18',
    'sm:col-span-19',
    'sm:col-span-20',
    'sm:col-span-21',
    'sm:col-span-22',
    'sm:col-span-23',
    'sm:col-span-24',
    'lg:col-span-1',
    'lg:col-span-2',
    'lg:col-span-3',
    'lg:col-span-4',
    'lg:col-span-5',
    'lg:col-span-6',
    'lg:col-span-7',
    'lg:col-span-8',
    'lg:col-span-9',
    'lg:col-span-10',
    'lg:col-span-11',
    'lg:col-span-12',
    'lg:col-span-13',
    'lg:col-span-14',
    'lg:col-span-15',
    'lg:col-span-16',
    'lg:col-span-17',
    'lg:col-span-18',
    'lg:col-span-19',
    'lg:col-span-20',
    'lg:col-span-21',
    'lg:col-span-22',
    'lg:col-span-23',
    'lg:col-span-24',
    'bg-[color:var(--color-charcoal)]',
    'bg-[color:var(--color-gray)]',
    'bg-[color:var(--color-silver)]',
    'bg-[color:var(--color-white)]',
    'bg-[color:var(--color-turquoise)]',
    'bg-[color:var(--color-blue)]',
    'bg-[color:var(--color-gold)]',
    'bg-[color:var(--color-green)]',
    'bg-[color:var(--color-orange)]',
    'bg-[color:var(--color-red)]',
    // {
    //   // Паттерн для классов с кастомными CSS-переменными по твоей схеме
    //   pattern: /(bg|text|border|outline|ring|shadow|fill|stroke)-\[color:var\(--color-(charcoal|gray|silver|white|turquoise|blue|gold|green|orange|red)\)\]/,
    // },
    // {
    //   // Паттерн для hover/focus-эффектов (по необходимости)
    //   pattern: /(hover|focus|active):((bg|text|border|outline|ring|shadow|fill|stroke)-\[color:var\(--color-(charcoal|gray|silver|white|turquoise|blue|gold|green|orange|red)\)\])/,
    // },
    // {
    //   pattern: /col-span-(1[0-2]|[1-9])/,
    //   variants: ['sm', 'md', 'lg', 'xl', '2xl'],
    // },
  ]
};
